  /courses/{course_id}/instructor/api/users_info:
    post:
      operationId: courses_instructor_api_users_info_create
      description: Testing
      parameters:
      - in: path
        name: course_id
        schema:
          type: string
          pattern: ^[^/+]+(/|\+)[^/+]+(/|\+)[^/?]+$
        required: true
      tags:
      - courses
      security:
      - {}
      responses:
        '200':
          description: No response body
  /courses/{course_id}/instructor/api/users_info2:
    post:
      operationId: courses_instructor_api_users_info2_create
      parameters:
      - in: path
        name: course_id
        schema:
          type: string
          pattern: ^[^/+]+(/|\+)[^/+]+(/|\+)[^/?]+$
        required: true
      tags:
      - courses
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInfo'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserInfo'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserInfo'
        required: true
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
          description: ''
